# Generated by Django 5.0.1 on 2024-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
