# Generated by Django 5.0.1 on 2024-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_remove_file_deleted_alter_course_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="branch",
        ),
        migrations.AddField(
            model_name="course",
            name="branch",
            field=models.ManyToManyField(to="notes.branch"),
        ),
    ]
