# Generated by Django 5.0.1 on 2024-02-05 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_course_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
