# Generated by Django 5.0.1 on 2024-02-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_branch_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodule",
            name="number_of_files",
            field=models.IntegerField(default=0),
        ),
    ]
