# Generated by Django 5.0.1 on 2024-02-06 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_course_credits_coursemodule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursemodule",
            options={"verbose_name": "Module"},
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("file_url", models.URLField(null=True)),
                ("file_name", models.CharField(max_length=200, null=True)),
                ("file_extension", models.CharField(max_length=200, null=True)),
                ("deleted", models.BooleanField(default=False, null=True)),
                (
                    "course_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notes.coursemodule",
                    ),
                ),
            ],
        ),
    ]
