# Generated by Django 5.0.1 on 2024-02-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_coursemodule_number_of_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemodule",
            name="number_of_files",
        ),
    ]
