# Generated by Django 5.0.1 on 2024-02-16 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_file_number_of_downloads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="approved",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
